/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    finishes: Finish;
    series: Series;
    wheels: Wheel;
    builds: Build;
    testimonials: Testimonial;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    finishes: FinishesSelect<false> | FinishesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    wheels: WheelsSelect<false> | WheelsSelect<true>;
    builds: BuildsSelect<false> | BuildsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'wheel-pricing': WheelPricing;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'wheel-pricing': WheelPricingSelect<false> | WheelPricingSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes".
 */
export interface Finish {
  id: string;
  name: string;
  /**
   * URL-friendly identifier (e.g. gloss-black, matte-bronze)
   */
  slug: string;
  description?: string | null;
  /**
   * Hex color code for swatch preview (e.g. #C9A84C)
   */
  hex?: string | null;
  /**
   * Optional swatch image
   */
  swatchImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheels".
 */
export interface Wheel {
  id: string;
  /**
   * Lowest base price per wheel for this design (in USD)
   */
  startingPricePerWheel?: number | null;
  name: string;
  /**
   * URL slug for the wheel (e.g. vfs-1)
   */
  slug: string;
  series: string | Series;
  description?: string | null;
  /**
   * Override global pricing rules for this wheel. Leave empty to use global Wheel Pricing.
   */
  pricingOverrides?: {
    useOverrides?: boolean | null;
    diameterOptions?:
      | {
          label: string;
          value: string;
          priceDelta: number;
          id?: string | null;
        }[]
      | null;
    widthOptions?:
      | {
          label: string;
          value: string;
          priceDelta: number;
          id?: string | null;
        }[]
      | null;
    constructionOptions?:
      | {
          label: string;
          value: string;
          priceDelta: number;
          id?: string | null;
        }[]
      | null;
    beadlockOptions?:
      | {
          label: string;
          value: string;
          priceDelta: number;
          id?: string | null;
        }[]
      | null;
  };
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Show on homepage featured section
   */
  featured?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds".
 */
export interface Build {
  id: string;
  /**
   * Display title for the build
   */
  title: string;
  slug: string;
  carMake: string;
  carModel: string;
  year: number;
  wheelUsed?: (string | null) | Wheel;
  /**
   * Finish name as shown on this build
   */
  finish?: string | null;
  photographerCredit?: string | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  customerName: string;
  location?: string | null;
  quote: string;
  /**
   * 1-5 stars
   */
  rating?: number | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  carDetails?: {
    make?: string | null;
    model?: string | null;
    year?: string | null;
  };
  /**
   * Wheel series or specific wheel of interest
   */
  wheelInterest?: (string | null) | Wheel;
  finishPreference?: string | null;
  boltPattern?: string | null;
  notes?: string | null;
  frontSpecs?: {
    diameter?: string | null;
    width?: string | null;
    offset?: string | null;
  };
  rearSpecs?: {
    diameter?: string | null;
    width?: string | null;
    offset?: string | null;
  };
  construction?: ('monoblock' | 'modular') | null;
  beadlock?: ('none' | 'beadlock' | 'rear_only') | null;
  estimatedPricePerWheel?: number | null;
  estimatedSetPrice?: number | null;
  status: 'new' | 'contacted' | 'quoted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'finishes';
        value: string | Finish;
      } | null)
    | ({
        relationTo: 'series';
        value: string | Series;
      } | null)
    | ({
        relationTo: 'wheels';
        value: string | Wheel;
      } | null)
    | ({
        relationTo: 'builds';
        value: string | Build;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishes_select".
 */
export interface FinishesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  hex?: T;
  swatchImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheels_select".
 */
export interface WheelsSelect<T extends boolean = true> {
  startingPricePerWheel?: T;
  name?: T;
  slug?: T;
  series?: T;
  description?: T;
  pricingOverrides?:
    | T
    | {
        useOverrides?: T;
        diameterOptions?:
          | T
          | {
              label?: T;
              value?: T;
              priceDelta?: T;
              id?: T;
            };
        widthOptions?:
          | T
          | {
              label?: T;
              value?: T;
              priceDelta?: T;
              id?: T;
            };
        constructionOptions?:
          | T
          | {
              label?: T;
              value?: T;
              priceDelta?: T;
              id?: T;
            };
        beadlockOptions?:
          | T
          | {
              label?: T;
              value?: T;
              priceDelta?: T;
              id?: T;
            };
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds_select".
 */
export interface BuildsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  carMake?: T;
  carModel?: T;
  year?: T;
  wheelUsed?: T;
  finish?: T;
  photographerCredit?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  customerName?: T;
  location?: T;
  quote?: T;
  rating?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  name?: T;
  email?: T;
  phone?: T;
  carDetails?:
    | T
    | {
        make?: T;
        model?: T;
        year?: T;
      };
  wheelInterest?: T;
  finishPreference?: T;
  boltPattern?: T;
  notes?: T;
  frontSpecs?:
    | T
    | {
        diameter?: T;
        width?: T;
        offset?: T;
      };
  rearSpecs?:
    | T
    | {
        diameter?: T;
        width?: T;
        offset?: T;
      };
  construction?: T;
  beadlock?: T;
  estimatedPricePerWheel?: T;
  estimatedSetPrice?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Main hero headline
   */
  heroHeadline?: string | null;
  /**
   * Optional subtext below headline
   */
  heroSubtext?: string | null;
  /**
   * Hero background image or video thumbnail
   */
  heroMedia?: (string | null) | Media;
  /**
   * Background image for Featured Wheels section
   */
  featuredWheelsBackground?: (string | null) | Media;
  /**
   * Background image for Why Forged section
   */
  aboutBackground?: (string | null) | Media;
  /**
   * Background image for Testimonials section
   */
  testimonialsBackground?: (string | null) | Media;
  /**
   * Background image for CTA / Your Build Starts Here section
   */
  ctaBackground?: (string | null) | Media;
  /**
   * Image for scroll parallax showcase (e.g. wheel close-up)
   */
  showcaseMedia?: (string | null) | Media;
  /**
   * Optional stats or tagline for ticker bar
   */
  statsTickerText?: string | null;
  socialLinks?:
    | {
        /**
         * e.g. Instagram, Facebook
         */
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary contact email for inquiries
   */
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-pricing".
 */
export interface WheelPricing {
  id: string;
  /**
   * Per-wheel price adjustments by diameter (e.g. 19", 20", 21").
   */
  diameterOptions?:
    | {
        label: string;
        value: string;
        priceDelta: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-wheel price adjustments by width (e.g. 9", 10.5").
   */
  widthOptions?:
    | {
        label: string;
        value: string;
        priceDelta: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Monoblock vs modular construction pricing.
   */
  constructionOptions?:
    | {
        label: string;
        value: string;
        priceDelta: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Beadlock options (Beadlock, No beadlock, Rear only).
   */
  beadlockOptions?:
    | {
        label: string;
        value: string;
        priceDelta: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroSubtext?: T;
  heroMedia?: T;
  featuredWheelsBackground?: T;
  aboutBackground?: T;
  testimonialsBackground?: T;
  ctaBackground?: T;
  showcaseMedia?: T;
  statsTickerText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wheel-pricing_select".
 */
export interface WheelPricingSelect<T extends boolean = true> {
  diameterOptions?:
    | T
    | {
        label?: T;
        value?: T;
        priceDelta?: T;
        id?: T;
      };
  widthOptions?:
    | T
    | {
        label?: T;
        value?: T;
        priceDelta?: T;
        id?: T;
      };
  constructionOptions?:
    | T
    | {
        label?: T;
        value?: T;
        priceDelta?: T;
        id?: T;
      };
  beadlockOptions?:
    | T
    | {
        label?: T;
        value?: T;
        priceDelta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}